import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  page: { gap: 14, paddingBottom: 32 },
  top: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 8,
  },
  brand: { fontSize: 20, fontWeight: '900' },
  row: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  themeBtn: { padding: 6 },
  primary: { borderRadius: 999, paddingHorizontal: 16, paddingVertical: 8 },
  primaryText: { fontWeight: '800', fontSize: 14 },
  link: { fontWeight: '700', fontSize: 14 },
  hero: { borderRadius: 20, padding: 20, marginHorizontal: 16, gap: 8 },
  heroTitle: { fontSize: 24, fontWeight: '800', textAlign: 'right' },
  heroSub: { fontSize: 14, textAlign: 'right' },
  searchBox: { borderRadius: 12, paddingHorizontal: 14, paddingVertical: 10, marginTop: 8 },
  searchInput: { fontSize: 15, textAlign: 'right' },
  tabs: { flexDirection: 'row', gap: 10, paddingHorizontal: 16 },
  tab: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 999,
    borderWidth: 1.5,
    borderColor: '#DCE6F7',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
  },
  tabText: { fontWeight: '700', fontSize: 15 },
  list: { paddingHorizontal: 16, gap: 12 },
  card: {
    borderRadius: 16,
    borderWidth: 1,
    borderStartWidth: 4,
    padding: 16,
    gap: 6,
  },
  cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  price: { fontSize: 19, fontWeight: '900' },
  badge: { fontSize: 12, fontWeight: '700', paddingHorizontal: 8, paddingVertical: 3, borderRadius: 999 },
  title: { fontSize: 17, fontWeight: '800', textAlign: 'right' },
  sub: { fontSize: 13, textAlign: 'right' },
  desc: { fontSize: 13, lineHeight: 18, textAlign: 'right', marginTop: 4 },
  footer: { borderRadius: 16, padding: 18, marginHorizontal: 16, marginTop: 12, gap: 4 },
  footerTitle: { fontSize: 16, fontWeight: '800', textAlign: 'center' },
  footerText: { fontSize: 12, textAlign: 'center' },
});
