import {
  DEAL_OWNED,
  DEAL_RENT,
  DEAL_SALE,
  FILTER_ALL,
  LISTED_BROKER,
  LISTED_PRIVATE,
  PRICE_WITH,
  PRICE_WITHOUT,
  PROPERTY_EXPENSE_ARNONA,
  PROPERTY_EXPENSE_COMMITTEE,
  PROPERTY_EXPENSE_INSURANCE,
  PROPERTY_EXPENSE_MORTGAGE,
  PROPERTY_EXPENSE_OTHER,
} from '@const';

export const HOME_FILTERS = [FILTER_ALL, DEAL_SALE, DEAL_RENT, DEAL_OWNED] as const;

export const HOME_DEAL_OPTIONS = [DEAL_OWNED, DEAL_SALE, DEAL_RENT] as const;

export const LISTED_FILTERS = [FILTER_ALL, LISTED_PRIVATE, LISTED_BROKER] as const;

export const PRICE_FILTERS = [FILTER_ALL, PRICE_WITH, PRICE_WITHOUT] as const;

export const PROPERTY_EXPENSE_OPTIONS = [
  PROPERTY_EXPENSE_MORTGAGE,
  PROPERTY_EXPENSE_ARNONA,
  PROPERTY_EXPENSE_COMMITTEE,
  PROPERTY_EXPENSE_INSURANCE,
  PROPERTY_EXPENSE_OTHER,
] as const;

export const PROPERTY_CITY_CHIPS = ['תל אביב', 'רמת גן', 'חיפה', 'ירושלים'] as const;
