import {
  DOCUMENT_TYPE_INSURANCE,
  DOCUMENT_TYPE_LICENSE,
  DOCUMENT_TYPE_OTHER,
  DOCUMENT_TYPE_TEST,
} from '@const';

export const DOCUMENT_TYPE_OPTIONS = [
  DOCUMENT_TYPE_LICENSE,
  DOCUMENT_TYPE_INSURANCE,
  DOCUMENT_TYPE_TEST,
  DOCUMENT_TYPE_OTHER,
] as const;
