import {
  EMPTY_ICON_DOCUMENT,
  EMPTY_ICON_MAINTENANCE,
  EMPTY_ICON_REMINDER,
  EMPTY_ICON_REPORT,
  EMPTY_ICON_VEHICLE,
  SVG_EMPTY_DOCUMENT,
  SVG_EMPTY_MAINTENANCE,
  SVG_EMPTY_REMINDER,
  SVG_EMPTY_REPORT,
  SVG_EMPTY_VEHICLE,
} from '@const';

export const EMPTY_ICON_SRC = {
  [EMPTY_ICON_VEHICLE]: SVG_EMPTY_VEHICLE,
  [EMPTY_ICON_DOCUMENT]: SVG_EMPTY_DOCUMENT,
  [EMPTY_ICON_MAINTENANCE]: SVG_EMPTY_MAINTENANCE,
  [EMPTY_ICON_REMINDER]: SVG_EMPTY_REMINDER,
  [EMPTY_ICON_REPORT]: SVG_EMPTY_REPORT,
} as const;
